name: CI

permissions:
  contents: read

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: solinas
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 22.x
        uses: actions/setup-node@v2
        with:
          node-version: 22.x
      - run: npm ci
      - run: npm run lint
  test:
    runs-on: solinas
    strategy:
      fail-fast: false
      matrix:
        node-version: [22.x, 20.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm i
      - run: node --test tests/embeddings.test.js # needed to load the model before running multiple tests
      - run: npm run test
